#!/usr/bin/env python
# coding: utf-8
               
from matplotlib.patches import Patch
   
CommonNamesDict = {'ND1':'ND1',
                   'NADH DEHYDROGENASE SUBUNIT 1':'ND1',
                   'ND2':'ND2',
                   'NADH DEHYDROGENASE SUBUNIT 2':'ND2',
                   'ND3':'ND3',
                   'NADH DEHYDROGENASE SUBUNIT 3':'ND3',
                   'ND4L':'ND4L',
                   'NADH DEHYDROGENASE SUBUNIT 4L':'ND4L',
                   'ND4':'ND4',
                   'NADH DEHYDROGENASE SUBUNIT 4':'ND4',
                   'ND5':'ND5',
                   'NADH DEHYDROGENASE SUBUNIT 5':'ND5',
                   'ND6':'ND6',
                   'NADH DEHYDROGENASE SUBUNIT 6':'ND6',
                   'COXI':'COX1',
                   'CYTOCHROME C OXIDASE SUBUNIT 1': 'COX1',
                   'CYTOCHROME OXIDASE SUBUNIT 1': 'COX1',
                   'COXII':'COX2',
                   'CYTOCHROME C OXIDASE SUBUNIT 2': 'COX2',
                   'CYTOCHROME OXIDASE SUBUNIT 2': 'COX2',
                   'COXIII':'COX3',
                   'CYTOCHROME C OXIDASE SUBUNIT 3': 'COX3',
                   'CYTOCHROME OXIDASE SUBUNIT 3': 'COX3',
                   'COX1':'COX1',
                   'COX2':'COX2',
                   'COX3':'COX3',
                   'CO1': 'COX1',
                   'CO2': 'COX2',
                   'CO3': 'COX3',
                   'ATP6':'ATPase6',
                   'ATP8':'ATPase8',
                   'ATPASE6':'ATPase6',
                   'ATPASE SUBUNIT 6':'ATPase6',
                   'ATP SYNTHASE F0 SUBUNIT 6':'ATPase6',
                   'ATPASE8':'ATPase8',
                   'ATPASE SUBUNIT 8':'ATPase8',
                   'ATP SYNTHASE F0 SUBUNIT 8':'ATPase8',
                   'CYTB':'Cytb',
                   'CYTOCHROME B':'Cytb',
                   'COB':'Cytb',
                   'APOCYTOCHROME B':'Cytb',
                   'S-RRNA':'12S rRNA',
                   'L-RRNA':'16S rRNA',
                   '12S RIBOSOMAL RNA':'12S rRNA',
                   '16S RIBOSOMAL RNA':'16S rRNA',
                   '12S RRNA':'12S rRNA',
                   '16S RRNA':'16S rRNA',
                   'SMALL SUBUNIT RIBOSOMAL RNA': '16S rRNA',
                   'LARGE SUBUNIT RIBOSOMAL RNA': '12S rRNA',
                   'RRN12':'12S rRNA',
                   'RRN16':'16S rRNA',
                   'RNR1':'12S rRNA',
                   'RNR2':'16S rRNA',
                   'D-LOOP':'D-loop',
                   'D_LOOP':'D-loop',
                   'PUTATIVE CONTROL REGION':'D-loop',
                   'POTENTIAL CONTROL REGION':'D-loop',
                   "CONTROL REGION":"D-loop",
                   "NON-CODING REGION":"D-loop",
                   "NONCODING REGION":"D-loop",
                   "NCR":"D-loop",
                   "A+T RICH REGION":"D-loop",
                   "AT RICH REGION":"D-loop",
                   "AT-RICH REGION":"D-loop",
                   'POTENTIAL CONTROL REGION; A+T RICH REGION':"D-loop",
                   'TRNA-HIS':'tRNA-His',
                   'TRNA-PRO':'tRNA-Pro',
                   'TRNA-THR':'tRNA-Thr',
                   'TRNA-TRP':'tRNA-Trp',
                   'TRNA-MET':'tRNA-Met',
                   'TRNA-ASP':'tRNA-Asp',
                   'TRNA-ALA':'tRNA-Ala',
                   'TRNA-GLN':'tRNA-Gln',
                   'TRNA-ILE':'tRNA-Ile',
                   'TRNA-ARG':'tRNA-Arg',
                   'TRNA-TYR':'tRNA-Tyr',
                   'TRNA-PHE':'tRNA-Phe',
                   'TRNA-LYS':'tRNA-Lys',
                   'TRNA-GLY':'tRNA-Gly',
                   'TRNA-ASN':'tRNA-Asn',
                   'TRNA-LEU':'tRNA-Leu',
                   'TRNA-GLU':'tRNA-Glu',
                   'TRNA-VAL':'tRNA-Val',
                   'TRNA-CYS':'tRNA-Cys',
                   'TRNA-SER':'tRNA-Ser',
                   'TRNF(GAA)': 'tRNA-Phe',
                   'TRNV(UAC)': 'tRNA-Val',
                   'TRNL(UAA)': 'tRNA-Leu',
                   'TRNI(GAU)': 'tRNA-Ile',
                   'TRNQ(UUG)': 'tRNA-Gln',
                   'TRNM(CAU)': 'tRNA-Met',
                   'TRNW(UCA)': 'tRNA-Trp',
                   'TRNA(UGC)': 'tRNA-Ala',
                   'TRNN(GUU)': 'tRNA-Asn',
                   'TRNC(GCA)': 'tRNA-Cys',
                   'TRNY(GUA)': 'tRNA-Tyr',
                   'TRNS(UGA)': 'tRNA-Ser',
                   'TRND(GUC)': 'tRNA-Asp',
                   'TRNK(UUU)': 'tRNA-Lys',
                   'TRNG(UCC)': 'tRNA-Gly',
                   'TRNR(UCG)': 'tRNA-Arg',
                   'TRNH(GUG)': 'tRNA-His',
                   'TRNS(GCU)': 'tRNA-Ser',
                   'TRNL(UAG)': 'tRNA-Leu',
                   'TRNE(UUC)': 'tRNA-Glu',
                   'TRNT(UGU)': 'tRNA-Thr',
                   'TRNP(UGG)': 'tRNA-Pro',
                   'TRNF': 'tRNA-Phe',
                   'TRNV': 'tRNA-Val',
                   'TRNL': 'tRNA-Leu',
                   'TRNL1': 'tRNA-Leu',
                   'TRNL2': 'tRNA-Leu',
                   'TRNI': 'tRNA-Ile',
                   'TRNQ': 'tRNA-Gln',
                   'TRNM': 'tRNA-Met',
                   'TRNW': 'tRNA-Trp',
                   'TRNA': 'tRNA-Ala',
                   'TRNN': 'tRNA-Asn',
                   'TRNC': 'tRNA-Cys',
                   'TRNY': 'tRNA-Tyr',
                   'TRNS': 'tRNA-Ser',
                   'TRNS1': 'tRNA-Ser',
                   'TRNS2': 'tRNA-Ser',
                   'TRND': 'tRNA-Asp',
                   'TRNK': 'tRNA-Lys',
                   'TRNG': 'tRNA-Gly',
                   'TRNR': 'tRNA-Arg',
                   'TRNH': 'tRNA-His',
                   'TRNS': 'tRNA-Ser',
                   'TRNL': 'tRNA-Leu',
                   'TRNE': 'tRNA-Glu',
                   'TRNT': 'tRNA-Thr',
                   'TRNP': 'tRNA-Pro',
                   }

FullName2AbbrName = {'ND1':'ND1',
                     'ND2':'ND2',
                     'ND3':'ND3',
                     'ND4L':'ND4L',
                     'ND4':'ND4',
                     'ND5':'ND5',
                     'ND6':'ND6',
                     'COX1':'COX1',
                     'COX2':'COX2',
                     'COX3':'COX3',
                     'ATPase6':'ATP6',
                     'ATPase8':'ATP8',
                     'Cytb':'Cytb',
                     'tRNA-Phe':'F',
                     'tRNA-Val':'V',
                     'tRNA-Leu':'L',
                     'tRNA-Ile':'I',
                     'tRNA-Gln':'Q',
                     'tRNA-Met':'M',
                     'tRNA-Trp':'W',
                     'tRNA-Ala':'A',
                     'tRNA-Asn':'N',
                     'tRNA-Cys':'C',
                     'tRNA-Tyr':'Y',
                     'tRNA-Ser':'S',
                     'tRNA-Asp':'D',
                     'tRNA-Lys':'K',
                     'tRNA-Gly':'G',
                     'tRNA-Arg':'R',
                     'tRNA-His':'H',
                     'tRNA-Ser':'S',
                     'tRNA-Leu':'L',
                     'tRNA-Glu':'E',
                     'tRNA-Thr':'T',
                     'tRNA-Pro':'P',
                     '12S rRNA':'12S',
                     '16S rRNA':'16S',
                     'D-loop':'NCR'}
                     
MTColors_by_default = {'source':"#000000",
            'ND1':'#FFEC00',
            'ND2':'#FFEC00',
            'ND3':'#FFEC00',
            'ND4L':'#FFEC00',
            'ND4':'#FFEC00',
            'ND5':'#FFEC00',
            'ND6':'#FFEC00',
            'COX1':'#97BE0D',
            'COX2':'#97BE0D',
            'COX3':'#97BE0D',
            'ATPase6':'#FF7F0E',
            'ATPase8':'#FF7F0E',
            'Cytb':'#AB259D',
            'tRNA-His':'#162983',
            'tRNA-Pro':'#162983',
            'tRNA-Thr':'#162983',
            'tRNA-Trp':'#162983',
            'tRNA-Met':'#162983',
            'tRNA-Asp':'#162983',
            'tRNA-Ala':'#162983',
            'tRNA-Gln':'#162983',
            'tRNA-Ile':'#162983',
            'tRNA-Arg':'#162983',
            'tRNA-Tyr':'#162983',
            'tRNA-Phe':'#162983',
            'tRNA-Lys':'#162983',
            'tRNA-Gly':'#162983',
            'tRNA-Asn':'#162983',
            'tRNA-Leu':'#162983',
            'tRNA-Glu':'#162983',
            'tRNA-Val':'#162983',
            'tRNA-Cys':'#162983',
            'tRNA-Ser':'#162983',
            '12S rRNA':'#E2001A',
            '16S rRNA':'#E2001A',
            'D-loop':'#9C9C9C'
           }
           
MTColors_by_OGDRAW = {'source':"#000000",
                      'ND1': '#ffec00ff',
                      'ND2': '#ffec00ff',
                      'ND3': '#ffec00ff',
                      'ND4L':'#ffec00ff',
                      'ND4': '#ffec00ff',
                      'ND5': '#ffec00ff',
                      'ND6': '#ffec00ff',
                      'COX1':  '#ffb4ffff',
                      'COX2': '#ffb4ffff',
                      'COX3':'#ffb4ffff',
                      'ATPase6':'#97be0dff',
                      'ATPase8':'#97be0dff',
                      'Cytb':'#ab259dff',
                      'tRNA-His':'#162983ff',
                      'tRNA-Pro':'#162983ff',
                      'tRNA-Thr':'#162983ff',
                      'tRNA-Trp':'#162983ff',
                      'tRNA-Met':'#162983ff',
                      'tRNA-Asp':'#162983ff',
                      'tRNA-Ala':'#162983ff',
                      'tRNA-Gln':'#162983ff',
                      'tRNA-Ile':'#162983ff',
                      'tRNA-Arg':'#162983ff',
                      'tRNA-Tyr':'#162983ff',
                      'tRNA-Phe':'#162983ff',
                      'tRNA-Lys':'#162983ff',
                      'tRNA-Gly':'#162983ff',
                      'tRNA-Asn':'#162983ff',
                      'tRNA-Leu':'#162983ff',
                      'tRNA-Glu':'#162983ff',
                      'tRNA-Val':'#162983ff',
                      'tRNA-Cys':'#162983ff',
                      'tRNA-Ser':'#162983ff',
                      '12S rRNA':'#e2001aff',
                      '16S rRNA':'#e2001aff',
                      'D-loop':'#ff8080ff'
                     }
                     
MTColors_by_MitoFish = {'source':"#000000",
                      'ND1': '#2a6332b2',
                      'ND2': '#2a6332b2',
                      'ND3': '#2a6332b2',
                      'ND4L':'#2a6332b2',
                      'ND4': '#2a6332b2',
                      'ND5': '#2a6332b2',
                      'ND6': '#2a6332b2',
                      'COX1':  '#feee50b2',
                      'COX2': '#feee50b2',
                      'COX3':'#feee50b2',
                      'ATPase6':'#9fbb3db2',
                      'ATPase8':'#9fbb3db2',
                      'Cytb':'#299E96',
                      'tRNA-His':'#172c7fb2',
                      'tRNA-Pro':'#172c7fb2',
                      'tRNA-Thr':'#172c7fb2',
                      'tRNA-Trp':'#172c7fb2',
                      'tRNA-Met':'#172c7fb2',
                      'tRNA-Asp':'#172c7fb2',
                      'tRNA-Ala':'#172c7fb2',
                      'tRNA-Gln':'#172c7fb2',
                      'tRNA-Ile':'#172c7fb2',
                      'tRNA-Arg':'#172c7fb2',
                      'tRNA-Tyr':'#172c7fb2',
                      'tRNA-Phe':'#172c7fb2',
                      'tRNA-Lys':'#172c7fb2',
                      'tRNA-Gly':'#172c7fb2',
                      'tRNA-Asn':'#172c7fb2',
                      'tRNA-Leu':'#172c7fb2',
                      'tRNA-Glu':'#172c7fb2',
                      'tRNA-Val':'#172c7fb2',
                      'tRNA-Cys':'#172c7fb2',
                      'tRNA-Ser':'#172c7fb2',
                      '12S rRNA':'#d1382ab2',
                      '16S rRNA':'#d1382ab2',
                      'D-loop':'#7d7d7db2'
                     }
                     
MTColors_by_MitoFish1 = {'source':"#000000",
                         'ND1': '#2a6332ff',
                         'ND2': '#2a6332ff',
                         'ND3': '#2a6332ff',
                         'ND4L':'#2a6332ff',
                         'ND4': '#2a6332ff',
                         'ND5': '#2a6332ff',
                         'ND6': '#2a6332ff',
                         'COX1':  '#feee50ff',
                         'COX2': '#feee50ff',
                         'COX3':'#feee50ff',
                         'ATPase6':'#9fbb3dff',
                         'ATPase8':'#9fbb3dff',
                         'Cytb':'#299E96',
                         'tRNA-His':'#172c7fff',
                         'tRNA-Pro':'#172c7fff',
                         'tRNA-Thr':'#172c7fff',
                         'tRNA-Trp':'#172c7fff',
                         'tRNA-Met':'#172c7fff',
                         'tRNA-Asp':'#172c7fff',
                         'tRNA-Ala':'#172c7fff',
                         'tRNA-Gln':'#172c7fff',
                         'tRNA-Ile':'#172c7fff',
                         'tRNA-Arg':'#172c7fff',
                         'tRNA-Tyr':'#172c7fff',
                         'tRNA-Phe':'#172c7fff',
                         'tRNA-Lys':'#172c7fff',
                         'tRNA-Gly':'#172c7fff',
                         'tRNA-Asn':'#172c7fff',
                         'tRNA-Leu':'#172c7fff',
                         'tRNA-Glu':'#172c7fff',
                         'tRNA-Val':'#172c7fff',
                         'tRNA-Cys':'#172c7fff',
                         'tRNA-Ser':'#172c7fff',
                         '12S rRNA':'#d1382aff',
                         '16S rRNA':'#d1382aff',
                         'D-loop':'#7d7d7dff'
                     }
                     
MTColors_by_Tan = {'source':"#000000",
                   'ND1': '#88c4e8ff',
                   'ND2': '#88c4e8ff',
                   'ND3': '#88c4e8ff',
                   'ND4L':'#88c4e8ff',
                   'ND4': '#88c4e8ff',
                   'ND5': '#88c4e8ff',
                   'ND6': '#88c4e8ff',
                   'COX1':  '#ea9c9dff',
                   'COX2': '#ea9c9dff',
                   'COX3':'#ea9c9dff',
                   'ATPase6':'#87d1d1ff',
                   'ATPase8':'#87d1d1ff',
                   'Cytb':'#d9dee7ff', 
                   'tRNA-His':'#f3d78aff',
                   'tRNA-Pro':'#f3d78aff',
                   'tRNA-Thr':'#f3d78aff',
                   'tRNA-Trp':'#f3d78aff',
                   'tRNA-Met':'#f3d78aff',
                   'tRNA-Asp':'#f3d78aff',
                   'tRNA-Ala':'#f3d78aff',
                   'tRNA-Gln':'#f3d78aff',
                   'tRNA-Ile':'#f3d78aff',
                   'tRNA-Arg':'#f3d78aff',
                   'tRNA-Tyr':'#f3d78aff',
                   'tRNA-Phe':'#f3d78aff',
                   'tRNA-Lys':'#f3d78aff',
                   'tRNA-Gly':'#f3d78aff',
                   'tRNA-Asn':'#f3d78aff',
                   'tRNA-Leu':'#f3d78aff',
                   'tRNA-Glu':'#f3d78aff',
                   'tRNA-Val':'#f3d78aff',
                   'tRNA-Cys':'#f3d78aff',
                   'tRNA-Ser':'#f3d78aff',
                   '12S rRNA':'#c74546ff',
                   '16S rRNA':'#c74546ff',
                   'D-loop':'#3d4e6aff'
                  }

MTColors_by_MitoZ = {'source':"#000000",
                   'ND1': '#8dd3c7ff',
                   'ND2': '#8dd3c7ff',
                   'ND3': '#8dd3c7ff',
                   'ND4L':'#8dd3c7ff',
                   'ND4': '#8dd3c7ff',
                   'ND5': '#8dd3c7ff',
                   'ND6': '#8dd3c7ff',
                   'COX1':  '#8dd3c7ff',
                   'COX2': '#8dd3c7ff',
                   'COX3':'#8dd3c7ff',
                   'ATPase6':'#8dd3c7ff',
                   'ATPase8':'#8dd3c7ff',
                   'Cytb':'#8dd3c7ff', 
                   'tRNA-His':'#fb8072ff',
                   'tRNA-Pro':'#fb8072ff',
                   'tRNA-Thr':'#fb8072ff',
                   'tRNA-Trp':'#fb8072ff',
                   'tRNA-Met':'#fb8072ff',
                   'tRNA-Asp':'#fb8072ff',
                   'tRNA-Ala':'#fb8072ff',
                   'tRNA-Gln':'#fb8072ff',
                   'tRNA-Ile':'#fb8072ff',
                   'tRNA-Arg':'#fb8072ff',
                   'tRNA-Tyr':'#fb8072ff',
                   'tRNA-Phe':'#fb8072ff',
                   'tRNA-Lys':'#fb8072ff',
                   'tRNA-Gly':'#fb8072ff',
                   'tRNA-Asn':'#fb8072ff',
                   'tRNA-Leu':'#fb8072ff',
                   'tRNA-Glu':'#fb8072ff',
                   'tRNA-Val':'#fb8072ff',
                   'tRNA-Cys':'#fb8072ff',
                   'tRNA-Ser':'#fb8072ff',
                   '12S rRNA':'#fdc086ff',
                   '16S rRNA':'#fdc086ff',
                   'D-loop':'#969696ff'
                  }
                  
MTColors_by_Chloroplot = {'source':"#000000",
                          'ND1': '#4C8805',
                          'ND2': '#4C8805',
                          'ND3': '#4C8805',
                          'ND4L':'#4C8805',
                          'ND4': '#4C8805',
                          'ND5': '#4C8805',
                          'ND6': '#4C8805',
                          'COX1':  '#299E96',
                          'COX2': '#299E96',
                          'COX3':'#299E96',
                          'ATPase6':'#9FBB3D',
                          'ATPase8':'#9FBB3D',
                          'Cytb':'#71B8A9', 
                          'tRNA-His':'#82B6E2',
                          'tRNA-Pro':'#82B6E2',
                          'tRNA-Thr':'#82B6E2',
                          'tRNA-Trp':'#82B6E2',
                          'tRNA-Met':'#82B6E2',
                          'tRNA-Asp':'#82B6E2',
                          'tRNA-Ala':'#82B6E2',
                          'tRNA-Gln':'#82B6E2',
                          'tRNA-Ile':'#82B6E2',
                          'tRNA-Arg':'#82B6E2',
                          'tRNA-Tyr':'#82B6E2',
                          'tRNA-Phe':'#82B6E2',
                          'tRNA-Lys':'#82B6E2',
                          'tRNA-Gly':'#82B6E2',
                          'tRNA-Asn':'#82B6E2',
                          'tRNA-Leu':'#82B6E2',
                          'tRNA-Glu':'#82B6E2',
                          'tRNA-Val':'#82B6E2',
                          'tRNA-Cys':'#82B6E2',
                          'tRNA-Ser':'#82B6E2',
                          '12S rRNA':'#D1382A',
                          '16S rRNA':'#D1382A',
                          'D-loop':'#7D7D7D'
                         }

MTColors_by_Grey = {'source':"#000000",
                          'ND1': '#555555',
                          'ND2': '#555555',
                          'ND3': '#555555',
                          'ND4L':'#555555',
                          'ND4': '#555555',
                          'ND5': '#555555',
                          'ND6': '#555555',
                          'COX1':  '#343434',
                          'COX2': '#343434',
                          'COX3':'#343434',
                          'ATPase6':'#727472',
                          'ATPase8':'#727472',
                          'Cytb':'#808080', 
                          'tRNA-His':'#D3D3D3',
                          'tRNA-Pro':'#D3D3D3',
                          'tRNA-Thr':'#D3D3D3',
                          'tRNA-Trp':'#D3D3D3',
                          'tRNA-Met':'#D3D3D3',
                          'tRNA-Asp':'#D3D3D3',
                          'tRNA-Ala':'#D3D3D3',
                          'tRNA-Gln':'#D3D3D3',
                          'tRNA-Ile':'#D3D3D3',
                          'tRNA-Arg':'#D3D3D3',
                          'tRNA-Tyr':'#D3D3D3',
                          'tRNA-Phe':'#D3D3D3',
                          'tRNA-Lys':'#D3D3D3',
                          'tRNA-Gly':'#D3D3D3',
                          'tRNA-Asn':'#D3D3D3',
                          'tRNA-Leu':'#D3D3D3',
                          'tRNA-Glu':'#D3D3D3',
                          'tRNA-Val':'#D3D3D3',
                          'tRNA-Cys':'#D3D3D3',
                          'tRNA-Ser':'#D3D3D3',
                          '12S rRNA':'#212121',
                          '16S rRNA':'#212121',
                          'D-loop':'#333333'
                         }


MTColors_by_IGV = {'source':"#000000",
                    'ND1': '#5050FFFF',
                    'ND2': '#CE3D32FF',
                    'ND3': '#749B58FF',
                    'ND4L':'#F0E685FF',
                    'ND4': '#466983FF',
                    'ND5': '#BA6338FF',
                    'ND6': '#5DB1DDFF',
                    'COX1':  '#802268FF',
                    'COX2': '#6BD76BFF',
                    'COX3':'#D595A7FF',
                    'ATPase6':'#924822FF',
                    'ATPase8':'#837B8DFF',
                    'Cytb':'#C75127FF', 
                    'tRNA-His':'#D58F5CFF',
                    'tRNA-Pro':'#7A65A5FF',
                    'tRNA-Thr':'#E4AF69FF',
                    'tRNA-Trp':'#3B1B53FF',
                    'tRNA-Met':'#CDDEB7FF',
                    'tRNA-Asp':'#612A79FF',
                    'tRNA-Ala':'#AE1F63FF',
                    'tRNA-Gln':'#E7C76FFF',
                    'tRNA-Ile':'#5A655EFF',
                    'tRNA-Arg':'#CC9900FF',
                    'tRNA-Tyr':'#99CC00FF',
                    'tRNA-Phe':'#A9A9A9FF',
                    'tRNA-Lys':'#CC9900FF',
                    'tRNA-Gly':'#99CC00FF',
                    'tRNA-Asn':'#33CC00FF',
                    'tRNA-Leu':'#00CC33FF',
                    'tRNA-Glu':'#00CC99FF',
                    'tRNA-Val':'#0099CCFF',
                    'tRNA-Cys':'#0A47FFFF',
                    'tRNA-Ser':'#4775FFFF',
                    '12S rRNA':'#FFC20AFF',
                    '16S rRNA':'#FFD147FF',
                    'D-loop':  '#990033FF'
                   }

MTColors_by_Set3 = {'source':"#000000",
                    'ND1': '#8DD3C7',
                    'ND2': '#8DD3C7',
                    'ND3': '#8DD3C7',
                    'ND4L':'#8DD3C7',
                    'ND4': '#8DD3C7',
                    'ND5': '#8DD3C7',
                    'ND6': '#8DD3C7',
                    'COX1':'#BEBADA',
                    'COX2':'#BEBADA',
                    'COX3':'#BEBADA',
                    'ATPase6':'#FDB462',
                    'ATPase8':'#FDB462',
                    'Cytb':'#80B1D3', 
                    'tRNA-His':'#FFFFB3',
                    'tRNA-Pro':'#FFFFB3',
                    'tRNA-Thr':'#FFFFB3',
                    'tRNA-Trp':'#FFFFB3',
                    'tRNA-Met':'#FFFFB3',
                    'tRNA-Asp':'#FFFFB3',
                    'tRNA-Ala':'#FFFFB3',
                    'tRNA-Gln':'#FFFFB3',
                    'tRNA-Ile':'#FFFFB3',
                    'tRNA-Arg':'#FFFFB3',
                    'tRNA-Tyr':'#FFFFB3',
                    'tRNA-Phe':'#FFFFB3',
                    'tRNA-Lys':'#FFFFB3',
                    'tRNA-Gly':'#FFFFB3',
                    'tRNA-Asn':'#FFFFB3',
                    'tRNA-Leu':'#FFFFB3',
                    'tRNA-Glu':'#FFFFB3',
                    'tRNA-Val':'#FFFFB3',
                    'tRNA-Cys':'#FFFFB3',
                    'tRNA-Ser':'#FFFFB3',
                    '12S rRNA':'#FB8072',
                    '16S rRNA':'#FB8072',
                    'D-loop': '#E5C494'
                   }

legend_elements_DEFAULT = [Patch(facecolor='#FFEC00', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                           Patch(facecolor='#97BE0D', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                           Patch(facecolor='#FF7F0E', edgecolor='black', label='ATP synthase'),
                           Patch(facecolor='#AB259D', edgecolor='black', label='Cytochrome b'),
                           Patch(facecolor='#162983', edgecolor='black', label='transfer RNA'),
                           Patch(facecolor='#E2001A', edgecolor='black', label='ribosomal RNA'),
                           Patch(facecolor='#9C9C9C', edgecolor='black', label='D-loop (Non-coding region)')
                          ]

legend_elements_OGDRAW = [Patch(facecolor='#ffec00ff', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                          Patch(facecolor='#ffb4ffff', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                          Patch(facecolor='#97be0dff', edgecolor='black', label='ATP synthase'),
                          Patch(facecolor='#ab259dff', edgecolor='black', label='Cytochrome b'),
                          Patch(facecolor='#162983ff', edgecolor='black', label='transfer RNA'),
                          Patch(facecolor='#e2001aff', edgecolor='black', label='ribosomal RNA'),
                          Patch(facecolor='#ff8080ff', edgecolor='black', label='D-loop (Non-coding region)')
                         ]


legend_elements_MitoFish = [Patch(facecolor='#2a6332b2', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                            Patch(facecolor='#feee50b2', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                            Patch(facecolor='#9fbb3db2', edgecolor='black', label='ATP synthase'),
                            Patch(facecolor='#299E96', edgecolor='black', label='Cytochrome b'),
                            Patch(facecolor='#172c7fb2', edgecolor='black', label='transfer RNA'),
                            Patch(facecolor='#d1382ab2', edgecolor='black', label='ribosomal RNA'),
                            Patch(facecolor='#7d7d7db2', edgecolor='black', label='D-loop (Non-coding region)')
                           ]  


legend_elements_MitoFish1 = [Patch(facecolor='#2a6332ff', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                            Patch(facecolor='#feee50ff', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                            Patch(facecolor='#9fbb3dff', edgecolor='black', label='ATP synthase'),
                            Patch(facecolor='#299E96', edgecolor='black', label='Cytochrome b'),
                            Patch(facecolor='#172c7fff', edgecolor='black', label='transfer RNA'),
                            Patch(facecolor='#d1382aff', edgecolor='black', label='ribosomal RNA'),
                            Patch(facecolor='#7d7d7dff', edgecolor='black', label='D-loop (Non-coding region)')
                           ]

legend_elements_Tan = [Patch(facecolor='#88c4e8ff', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                       Patch(facecolor='#ea9c9dff', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                       Patch(facecolor='#87d1d1ff', edgecolor='black', label='ATP synthase'),
                       Patch(facecolor='#d9dee7ff', edgecolor='black', label='Cytochrome b'),
                       Patch(facecolor='#f3d78aff', edgecolor='black', label='transfer RNA'),
                       Patch(facecolor='#c74546ff', edgecolor='black', label='ribosomal RNA'),
                       Patch(facecolor='#3d4e6aff', edgecolor='black', label='D-loop (Non-coding region)')
                      ]

legend_elements_MitoZ = [Patch(facecolor='#8dd3c7ff', edgecolor='black', label='Protein codon genes'),
                         Patch(facecolor='#fb8072ff', edgecolor='black', label='transfer RNA genes'),
                         Patch(facecolor='#fdc086ff', edgecolor='black', label='ribosomal RNA genes'),
                         Patch(facecolor='#969696ff', edgecolor='black', label='D-loop (Non-coding region)')
                        ]

legend_elements_Chloroplot = [Patch(facecolor='#4C8805', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                       Patch(facecolor='#299E96', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                       Patch(facecolor='#9FBB3D', edgecolor='black', label='ATP synthase'),
                       Patch(facecolor='#71B8A9', edgecolor='black', label='Cytochrome b'),
                       Patch(facecolor='#82B6E2', edgecolor='black', label='transfer RNA'),
                       Patch(facecolor='#D1382A', edgecolor='black', label='ribosomal RNA'),
                       Patch(facecolor='#7D7D7D', edgecolor='black', label='D-loop (Non-coding region)')
]

legend_elements_Grey = [Patch(facecolor='#555555', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                       Patch(facecolor='#343434', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                       Patch(facecolor='#727472', edgecolor='black', label='ATP synthase'),
                       Patch(facecolor='#808080', edgecolor='black', label='Cytochrome b'),
                       Patch(facecolor='#D3D3D3', edgecolor='black', label='transfer RNA'),
                       Patch(facecolor='#212121', edgecolor='black', label='ribosomal RNA'),
                       Patch(facecolor='#333333', edgecolor='black', label='D-loop (Non-coding region)')
]


legend_elements_Set3 = [Patch(facecolor='#8DD3C7', edgecolor='black', label='Complex I (NADH dehydrogenase)'),
                       Patch(facecolor='#BEBADA', edgecolor='black', label='Complex IV (Cytochrome c oxidase)'),
                       Patch(facecolor='#FDB462', edgecolor='black', label='ATP synthase'),
                       Patch(facecolor='#80B1D3', edgecolor='black', label='Cytochrome b'),
                       Patch(facecolor='#FFFFB3', edgecolor='black', label='transfer RNA'),
                       Patch(facecolor='#FB8072', edgecolor='black', label='ribosomal RNA'),
                       Patch(facecolor='#E5C494', edgecolor='black', label='D-loop (Non-coding region)')
]

legend_elements_IGV = [Patch(facecolor=MTColors_by_IGV[i], edgecolor='black', label=i) for i in MTColors_by_IGV if i!="source"]

MTColors = {"CHEN": MTColors_by_default,
            "OGDRAW": MTColors_by_OGDRAW,
            "MITOFISH":MTColors_by_MitoFish,
            "MITOFISH1":MTColors_by_MitoFish1,
            "MITOZ":MTColors_by_MitoZ,
            "TAN":MTColors_by_Tan,
            "CHLOROPLOT":MTColors_by_Chloroplot,
            "GREY":MTColors_by_Grey,
            "IGV":MTColors_by_IGV,
            "GGGENES":MTColors_by_Set3
            }


MTColors_legends = {"CHEN": legend_elements_DEFAULT,
                    "OGDRAW": legend_elements_OGDRAW,
                    "MITOFISH":legend_elements_MitoFish,
                    "MITOFISH1":legend_elements_MitoFish1,
                    "MITOZ":legend_elements_MitoZ,
                    "TAN":legend_elements_Tan,
                    "CHLOROPLOT":legend_elements_Chloroplot,
                    "GREY":legend_elements_Grey,
                    "IGV":legend_elements_IGV,
                    "GGGENES":legend_elements_Set3
                   }
